language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: Z/3T6DL0oo8EXgJ2h7/Zl1UfSAexgci3xD14wHjYKV2Ey2Bb6o2LipztxAVnsiVBNhvLifqhyy09W/ktpjsO7zlKHtPSh/NmsxLcuYiFt02gdTOB5cl1bnFlG6S4g2zQiOnSMRBohtu9eWV4ARzy42jfAFs/gJjIFuF3yW/9KrKw9jNnZgew11XqpOV78jg8pf0Eknm9f51zoH8kKce7Z5Y9P0Z9WvudnxVPMfwmqgAjekCh57rD6ylcN7EJBe+DDR0DlznIKus7yYlfTIthwoiNzzSEr/164ePtCSk/7GCZzhZ3T9DDIVem3C3cQM+3TYTzq/oyqGO7VfMsxoyggrUjmizYdobYZiu3IVsZxMYNiu+xfiPJdQ7ZO5KWAkXSpfQVGSOGcUaHXjj6A3AZXdRYFC2N0NbI6vr5gm+N/rqB/KaVFzjDr3ye0voAiVVlQn/hboPyBmikIc//IwCwXYzM+Ut3UvPg4f3x/zFQsK3VRN7ydH72G0fEn8ZiVWySqhZZNty0bmFp4Oc+fhHCv29ZzqZXIH/NJ4949sAhTH5/+uID3+VuBvt3jKjAI27Rpx87RrZ6uTN/AgGi0yR7FzR1XKz3sopo5J7BZcYP9VdgDz0a49xoyk62Sj1fGdi/+7tOwVz0LnCVYHPg6iC9V4hEkBEVXbrkO7yKtieWZ5A=
  file: build/libs/attribute-match-node-enhancer*.jar
  on:
    repo: rundeck-plugins/attribute-match-node-enhancer
    tags: true
  file_glob: true
  skip_cleanup: true
